name: KPM Push Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # 安装 go 环境
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      # go install 安装 kpm 
      - name: Install kpm
        run: go install kcl-lang.io/kpm@latest

      # kpm login and kpm push
      - name: Push kpm project
        env:
          # kpm 支持通过环境变量 KPM_REG 和 KPM_REPO 自定义 OCI Registry 地址和仓库名
          # 如果不设置，默认的 OCI Registry 地址为 ghcr.io，仓库名为 kcl-lang.
          # 这个例子中，设置为 ghcr.io 和 zong-zhe
          # KPM_REG: "ghcr.io"
          # KPM_REPO: "zong-zhe"
        run: kpm login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io && kpm push

      - name: Run kpm project
        # 测试是否 push 成功
        run: kpm run oci://ghcr.io/zong-zhe/mykcl --tag 0.0.1
